---
apiVersion: apps/v1
kind: Pod
metadata:
  name: searx
spec:
  containers:
    - name: searx
      image: searx:local
      env:
        - name: SEARXNG_VALKEY_URL
          value: redis://localhost:6379/0
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://localhost:4317"
      ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
    - name: redis
      image: docker.io/valkey/valkey:8.1.2
      ports:
        - name: redis
          containerPort: 6379
    - name: prometheus
      image: docker.io/prom/prometheus:v3.4.2
      args:
        - --config.file=/etc/prometheus.yaml
        - --web.enable-remote-write-receiver
        - --enable-feature=exemplar-storage
        - --enable-feature=native-histograms
      ports:
        - name: prometheus
          containerPort: 9090
          hostPort: 8090
      volumeMounts:
        - name: prometheus
          mountPath: /etc/prometheus.yaml
          readOnly: true
    - name: tempo
      image: docker.io/grafana/tempo:2.8.1
      args:
        - -config.file=/etc/tempo.yaml
      volumeMounts:
        - name: tempo
          mountPath: /etc/tempo.yaml
          readOnly: true
      ports:
        - name: tempo
          containerPort: 3200
        - name: tempo-grpc
          containerPort: 9095
        - name: otlp-grpc
          containerPort: 4317
        - name: otlp-http
          containerPort: 4318
        - name: zipkin
          containerPort: 9411
        - name: jaeger-ingest
          containerPort: 14268
    - name: grafana
      image: docker.io/grafana/grafana:12.0.2
      env:
        # Disable authentication
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        # ?
        - name: GF_FEATURE_TOGGLES_ENABLE
          value: "traceqlEditor metricsSummary"
        - name: GF_INSTALL_PLUGINS
          value: "https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app"
      ports:
        - name: http
          containerPort: 3000
          hostPort: 8081
      volumeMounts:
        - name: grafana
          mountPath: /etc/grafana/provisioning:z
          readOnly: true
  volumes:
    - name: prometheus
      hostPath:
        path: prometheus.yaml
        type: File
    - name: tempo
      hostPath:
        path: tempo.yaml
        type: File
    - name: grafana
      hostPath:
        path: grafana
        type: Directory
