---
apiVersion: apps/v1
kind: Pod
metadata:
  name: searx
spec:
  containers:
    - name: searx
      image: searx:local
      env:
        - name: SEARXNG_VALKEY_URL
          value: redis://localhost:6379/0
      ports:
        - name: http
          containerPort: 8080
          hostPort: 8080
    - name: redis
      image: docker.io/valkey/valkey:8.1.4
      ports:
        - name: redis
          containerPort: 6379
    - name: prometheus
      image: docker.io/prom/prometheus:v3.7.1
      args:
        - --config.file=/etc/prometheus.yaml
        - --web.enable-remote-write-receiver
        - --enable-feature=exemplar-storage
        - --enable-feature=native-histograms
      ports:
        - name: prometheus
          containerPort: 9090
          hostPort: 8090
      volumeMounts:
        - name: prometheus
          mountPath: /etc/prometheus.yaml
          readOnly: true
    - name: grafana
      image: docker.io/grafana/grafana:12.2.1
      env:
        # Disable authentication
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
      ports:
        - name: http
          containerPort: 3000
          hostPort: 8081
      volumeMounts:
        - name: grafana
          mountPath: /etc/grafana/provisioning:z
          readOnly: true
  volumes:
    - name: prometheus
      hostPath:
        path: prometheus.yaml
        type: File
    - name: grafana
      hostPath:
        path: grafana
        type: Directory
