{
 "title": "Searx",
 "description": "Metrics from SearxNG",
 "tags": [ "searx" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "datasource_loki", "label": "Datasource Loki", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(searxng_engines_reliability_total, job)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(searxng_engines_reliability_total, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reliability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min by (engine_name) (\n  searxng_engines_reliability_total{job=~\"$job\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (engine_name) (\n  searxng_engines_response_time_total_seconds{job=~\"$job\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Response http time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (engine_name) (\n  searxng_engines_response_time_http_seconds{job=~\"$job\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Response processing time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (engine_name) (\n  searxng_engines_response_time_processing_seconds{job=~\"$job\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (engine_name) (\n  searxng_engines_request_count_total{job=~\"$job\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Result count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (engine_name) (\n  searxng_engines_result_count_total{job=~\"$job\", pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{pod=~\"$pod\"}"
    }
   ]
  }
 ]
}