---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: quotes
          image: ghcr.io/yellowhat/searx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
