---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  type: ClusterIP
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: searxng
  sessionAffinity: None
