---
name: Pipeline

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    uses: ./.github/workflows/00_build.yaml
    permissions:
      contents: read  # Required to checkout
      packages: write # Required to push container image
