---
name: Sync with upstream

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 1 * * *"  # UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    # Cannot use default GITHUB_TOKEN, as PRs created by this token will not trigger a new workflow run.
    # Use a Fine-grained Personal Access Token (PAT) with scopes:
    # - contents: Read and Write
    # - pull-requests: Read and Write
    # https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
    # permissions:
    #   actions: write
    #   contents: write
    #   # Also Settings > Actions > General
    #   # [x] Allow GitHub Actions to create and approve pull requests
    #   pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Remove existing folder
        run: rm -rf searxng

      - name: Clone external repository
        run: |
          git clone https://github.com/searxng/searxng

      - name: Get commit SHA and messages
        id: sha
        run: |
          OLD_SHA=""
          if [ -f .github/.synced_commit ]; then
            OLD_SHA=$(cat .github/.synced_commit)
          fi
          echo "[INFO] Old sha: $OLD_SHA"
          
          pushd searxng
          NEW_SHA=$(git log -1 --format=%h)
          echo "sha=$NEW_SHA" | tee -a "$GITHUB_OUTPUT"
          echo "$NEW_SHA" | tee .github/.synced_commit

          if [ -n "$OLD_SHA" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" ${OLD_SHA}..HEAD)
          else
            COMMITS=$(git log --pretty=format:"- %s (%h)" -10)
          fi

          echo "commits<<EOF" | tee -a "$GITHUB_OUTPUT"
          echo "$COMMITS" | tee -a "$GITHUB_OUTPUT"
          echo "EOF" | tee -a "$GITHUB_OUTPUT"

          popd
          rm -rf searxng/.git

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.SEARX_PR_TOKEN }}
          title: 'Update SearXNG to ${{ steps.sha.outputs.sha }}'
          commit-message: 'Update SearXNG to ${{ steps.sha.outputs.sha }}'
          body: |
            Update SearXNG to ${{ steps.sha.outputs.sha }}

            ## New commits:
            ${{ steps.sha.outputs.commits }}
          branch: update-searxng
