---
name: Sync with upstream

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 1 * * *"  # UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      # Also Settings > Actions > General
      # [x] Allow GitHub Actions to create and approve pull requests
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Remove existing folder
        run: rm -rf searxng

      - name: Clone external repository
        run: |
          git clone https://github.com/searxng/searxng --depth 1
          rm -rf searxng/.git

      - name: Get commit SHA
        id: sha
        run: |
          cd searxng
          echo "sha=$(git log -1 --format=%h)" >>$GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          title: 'Update SearXNG to ${{ steps.sha.outputs.sha }}'
          commit-message: 'Update SearXNG to ${{ steps.sha.outputs.sha }}'
          body: |
            Update SearXNG to ${{ steps.sha.outputs.sha }}
          branch: update-searxng